import React, { useMemo } from 'react';
import { BudgetCategory, Transaction, TransactionLabel } from '../../types';
import { getBudgetColor } from './budgetColors';
import { getBudgetIcon } from './getBudgetIcon';

interface CategoryBarChartProps {
  budgets: BudgetCategory[];
  transactions: Transaction[];
  projectedTransactions?: Transaction[];
  totalIncome: number;
  isTutorialMode?: boolean;
  theme?: 'light' | 'dark';
}

// Fraction of budget limit used to generate placeholder tutorial data
const TUTORIAL_SPEND_RATIO = 0.6;

/** Accumulate transaction amounts into a spend map keyed by budget name */
function accumulateSpend(
  txs: Transaction[],
  budgetNameById: Map<string, string>,
  spendMap: Map<string, number>,
) {
  for (const tx of txs) {
    if (tx.splits && tx.splits.length > 0) {
      for (const split of tx.splits) {
        const catName = budgetNameById.get(split.budget_id) || 'Other';
        spendMap.set(catName, (spendMap.get(catName) || 0) + (split.amount || 0));
      }
    } else {
      const catName = tx.budget_id ? (budgetNameById.get(tx.budget_id) || 'Other') : 'Other';
      spendMap.set(catName, (spendMap.get(catName) || 0) + tx.amount);
    }
  }
}

const CategoryBarChart: React.FC<CategoryBarChartProps> = ({
  budgets,
  transactions,
  projectedTransactions = [],
  totalIncome,
  isTutorialMode = false,
  theme = 'dark',
}) => {
  const safeBudgets = Array.isArray(budgets) ? budgets : [];

  const { now, year, month, todayMs } = useMemo(() => {
    const n = new Date();
    const d = new Date(Date.UTC(n.getUTCFullYear(), n.getUTCMonth(), n.getUTCDate()));
    return { now: n, year: n.getUTCFullYear(), month: n.getUTCMonth(), todayMs: d.getTime() };
  }, []);

  // Current-month actual (past) transactions — not projected, date <= today
  const actualTxs = useMemo(() => {
    const txs = Array.isArray(transactions) ? transactions : [];
    if (isTutorialMode && txs.length === 0 && safeBudgets.length > 0) {
      return safeBudgets.map((b, i) => ({
        id: `__tutorial_bar_${i}__`,
        vendor: 'Tutorial',
        amount: Math.round((b.totalLimit || 500) * TUTORIAL_SPEND_RATIO * 100) / 100,
        date: now.toISOString(),
        budget_id: b.id,
        user_id: '__tutorial__',
        is_projected: false,
        label: TransactionLabel.MANUAL,
        created_at: now.toISOString(),
      })) as Transaction[];
    }
    return txs.filter((tx) => {
      const d = new Date(tx.date);
      return (
        d.getUTCFullYear() === year &&
        d.getUTCMonth() === month &&
        !tx.is_projected &&
        d.getTime() <= todayMs
      );
    });
  }, [transactions, isTutorialMode, safeBudgets, year, month, todayMs, now]);

  // Future + projected transactions this month (is_projected OR date > today, within this month)
  const upcomingTxs = useMemo(() => {
    const txs = Array.isArray(transactions) ? transactions : [];
    // Non-projected future transactions + already-projected entries in state.transactions
    const fromState = txs.filter((tx) => {
      const d = new Date(tx.date);
      const inMonth = d.getUTCFullYear() === year && d.getUTCMonth() === month;
      if (!inMonth) return false;
      // Include if projected, or if it's a future non-projected transaction
      return tx.is_projected || d.getTime() > todayMs;
    });
    // Projected transactions generated by Dashboard (from recurring entries)
    const projTxs = Array.isArray(projectedTransactions) ? projectedTransactions : [];
    return [...fromState, ...projTxs];
  }, [transactions, projectedTransactions, year, month, todayMs]);

  // Per-category spending with actual vs upcoming split
  const categoryData = useMemo(() => {
    const budgetNameById = new Map<string, string>();
    safeBudgets.forEach((b) => budgetNameById.set(b.id, b.name));

    const actualMap = new Map<string, number>();
    const upcomingMap = new Map<string, number>();
    safeBudgets.forEach((b) => {
      actualMap.set(b.name, 0);
      upcomingMap.set(b.name, 0);
    });

    accumulateSpend(actualTxs, budgetNameById, actualMap);
    accumulateSpend(upcomingTxs, budgetNameById, upcomingMap);

    return safeBudgets.map((b, i) => ({
      name: b.name,
      actual: actualMap.get(b.name) || 0,
      upcoming: upcomingMap.get(b.name) || 0,
      limit: b.totalLimit,
      color: getBudgetColor(b.name, i),
    }));
  }, [safeBudgets, actualTxs, upcomingTxs]);

  const totalSpent = categoryData.reduce((sum, c) => sum + c.actual + c.upcoming, 0);

  if (categoryData.length === 0) {
    return (
      <div className="w-full mb-2">
        <div className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-md rounded-3xl p-4 border border-slate-200/40 dark:border-slate-700/40 shadow-lg">
          <div className="text-center py-6">
            <p className="text-sm font-bold text-slate-500 dark:text-slate-400 mb-1">No spending data yet</p>
            <p className="text-xs text-slate-400 dark:text-slate-500">
              Add transactions to see your category breakdown.
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div id="spending-flow-chart" className="w-full mb-1 shrink-0">
      {/* SVG defs for hatched patterns — one per category color */}
      <svg width="0" height="0" style={{ position: 'absolute' }}>
        <defs>
          {categoryData.map((cat) => (
            <pattern
              key={`hatch-${cat.name}`}
              id={`hatch-${cat.name.replace(/\s+/g, '-')}`}
              width="6"
              height="6"
              patternUnits="userSpaceOnUse"
              patternTransform="rotate(45)"
            >
              <line x1="0" y1="0" x2="0" y2="6" stroke={cat.color.primary} strokeWidth="2.5" strokeOpacity="0.55" />
            </pattern>
          ))}
        </defs>
      </svg>

      <div className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-md rounded-3xl p-4 border border-slate-200/40 dark:border-slate-700/40 shadow-lg">
        {/* Header */}
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400 dark:text-slate-500">
            This Month
          </h3>
          <div className="flex items-center gap-1.5">
            <span className="text-[10px] font-black text-slate-500 dark:text-slate-400">
              ${totalSpent.toLocaleString(undefined, { maximumFractionDigits: 0 })}
            </span>
            {totalIncome > 0 && (
              <>
                <span className="text-[10px] font-medium text-slate-300 dark:text-slate-600">/</span>
                <span className="text-[10px] font-bold text-slate-400 dark:text-slate-500">
                  ${totalIncome.toLocaleString(undefined, { maximumFractionDigits: 0 })}
                </span>
              </>
            )}
          </div>
        </div>

        {/* Category rows */}
        <div className="space-y-4">
          {categoryData.map((cat) => {
            const total = cat.actual + cat.upcoming;
            const actualPct = cat.limit > 0 ? Math.min((cat.actual / cat.limit) * 100, 100) : 0;
            const upcomingPct = cat.limit > 0 ? Math.min((cat.upcoming / cat.limit) * 100, 100 - actualPct) : 0;
            const isOver = total > cat.limit;

            return (
              <div key={cat.name} className="flex items-center gap-2.5">
                {/* Icon — centered */}
                <div
                  className="flex-shrink-0 w-8 h-8 rounded-lg flex items-center justify-center"
                  style={{ backgroundColor: `${cat.color.primary}15`, color: cat.color.primary }}
                >
                  {getBudgetIcon(cat.name)}
                </div>

                {/* Bar + label */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center justify-between mb-0.5">
                    <span className="text-[9px] font-black uppercase tracking-wider text-slate-400 dark:text-slate-500 truncate">
                      {cat.name}
                    </span>
                    <span className={`text-[9px] font-black tracking-tight ml-2 ${
                      isOver
                        ? 'text-rose-500'
                        : 'text-slate-400 dark:text-slate-500'
                    }`}>
                      ${total.toFixed(0)}
                      <span className="text-slate-300 dark:text-slate-600 font-bold"> / ${cat.limit.toFixed(0)}</span>
                    </span>
                  </div>
                  {/* Bar track */}
                  <div className="h-8 rounded-full overflow-hidden bg-slate-100 dark:bg-slate-800/60 relative">
                    {/* Solid bar — actual past spend */}
                    <div
                      className="absolute inset-y-0 left-0 rounded-full transition-all duration-700 ease-out"
                      style={{
                        width: `${actualPct}%`,
                        backgroundColor: cat.color.primary,
                        minWidth: cat.actual > 0 ? '3px' : '0px',
                      }}
                    />
                    {/* Hatched bar — upcoming/projected spend, stacked after solid */}
                    {cat.upcoming > 0 && (
                      <svg
                        className="absolute inset-y-0 h-full transition-all duration-700 ease-out"
                        style={{
                          left: `${actualPct}%`,
                          width: `${upcomingPct}%`,
                          minWidth: '3px',
                        }}
                        preserveAspectRatio="none"
                      >
                        <rect
                          width="100%"
                          height="100%"
                          rx="9999"
                          fill={`url(#hatch-${cat.name.replace(/\s+/g, '-')})`}
                        />
                      </svg>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default CategoryBarChart;
