import React, { useState } from 'react';
import type { BudgetCategory, Transaction } from '../../../types';

interface BudgetSummary {
  name: string;
  limit: number;
  spent: number;
}

interface TransactionSummary {
  vendor: string;
  amount: number;
  date: string;
  category: string;
}

interface ReportSectionProps {
  budgets: BudgetCategory[];
  transactions: Transaction[];
  userName?: string;
  totalIncome?: number;
}

const ReportSection: React.FC<ReportSectionProps> = ({
  budgets,
  transactions,
  userName,
  totalIncome,
}) => {
  const [reportOpened, setReportOpened] = useState(false);

  /** Build a budget summary from current budgets + transactions for the report. */
  const buildBudgetSummary = (): BudgetSummary[] => {
    const now = new Date();
    const currentMonth = now.getMonth();
    const currentYear = now.getFullYear();

    return budgets.map((b) => {
      const spent = transactions
        .filter((tx) => {
          if (tx.is_projected) return false;
          if (tx.budget_id !== b.id) return false;
          const txDate = new Date(tx.date);
          return txDate.getMonth() === currentMonth && txDate.getFullYear() === currentYear;
        })
        .reduce((sum, tx) => sum + tx.amount, 0);

      return { name: b.name, limit: b.totalLimit, spent };
    });
  };

  /** Build a transaction list for the current month for the report. */
  const buildTransactionList = (): TransactionSummary[] => {
    const now = new Date();
    const currentMonth = now.getMonth();
    const currentYear = now.getFullYear();

    const budgetNameById = new Map(budgets.map((b) => [b.id, b.name]));

    return transactions
      .filter((tx) => {
        if (tx.is_projected) return false;
        const txDate = new Date(tx.date);
        return txDate.getMonth() === currentMonth && txDate.getFullYear() === currentYear;
      })
      .map((tx) => ({
        vendor: tx.vendor,
        amount: tx.amount,
        date: tx.date,
        category: tx.budget_id ? budgetNameById.get(tx.budget_id) || 'Other' : 'Other',
      }));
  };

  /** Build a plain-text version of the report suitable for email body. */
  const buildPlainTextReport = (
    budgetSummary: BudgetSummary[],
    transactionList: TransactionSummary[],
    income: number,
  ): string => {
    const now = new Date();
    const monthYear = now.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
    const title = userName ? `${userName}'s Budget Report` : 'Your Budget Report';

    const totalSpent = budgetSummary.reduce((sum, b) => sum + b.spent, 0);
    const totalBudget = budgetSummary.reduce((sum, b) => sum + b.limit, 0);
    const remaining = income > 0 ? income - totalSpent : totalBudget - totalSpent;

    let text = `COVAULT — ${title}\n${monthYear}\n`;
    text += `${'─'.repeat(40)}\n\n`;

    text += `OVERVIEW\n`;
    text += `  Spent:     $${totalSpent.toFixed(2)}\n`;
    text += `  Budget:    $${totalBudget.toFixed(2)}\n`;
    text += `  Remaining: $${remaining.toFixed(2)}\n\n`;

    text += `BUDGET BREAKDOWN\n`;
    text += `${'─'.repeat(40)}\n`;
    for (const b of budgetSummary) {
      const pct = b.limit > 0 ? Math.round((b.spent / b.limit) * 100) : 0;
      const rem = b.limit - b.spent;
      const status = pct >= 100 ? 'OVER' : pct >= 75 ? 'CAUTION' : 'OK';
      text += `  ${b.name}: $${b.spent.toFixed(2)} / $${b.limit.toFixed(2)} (${pct}%) [${status}] — $${rem.toFixed(2)} left\n`;
    }

    if (transactionList.length > 0) {
      text += `\nRECENT TRANSACTIONS (${transactionList.length} total)\n`;
      text += `${'─'.repeat(40)}\n`;
      const sorted = [...transactionList].sort(
        (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime(),
      );
      const display = sorted.slice(0, 30);
      for (const tx of display) {
        const d = new Date(tx.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
        text += `  ${d}  ${tx.vendor}  $${tx.amount.toFixed(2)}  (${tx.category})\n`;
      }
      if (transactionList.length > 30) {
        text += `  ... and ${transactionList.length - 30} more\n`;
      }
    }

    text += `\n${'─'.repeat(40)}\nGenerated by Covault — Budget Tracking Made Simple`;

    return text;
  };

  const handleGenerateReport = () => {
    const budgetSummary = buildBudgetSummary();
    const transactionList = buildTransactionList();
    const income = totalIncome ?? 0;

    const now = new Date();
    const subject = `Covault Budget Report – ${now.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`;
    const body = buildPlainTextReport(budgetSummary, transactionList, income);

    // Use mailto: to open the user's email client with the report pre-filled
    const mailtoUrl = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(mailtoUrl, '_blank');

    setReportOpened(true);
    setTimeout(() => setReportOpened(false), 2500);
  };

  return (
    <div id="settings-reports-container" className="p-5 bg-slate-50 dark:bg-slate-800/50 rounded-3xl border border-slate-100 dark:border-slate-800/60">
      <div className="flex flex-col mb-3">
        <span className="text-[11px] font-black uppercase tracking-[0.2em] text-slate-500 dark:text-slate-400">
          Budget Report
        </span>
        <p className="text-[10px] text-slate-400 dark:text-slate-500 mt-0.5 leading-relaxed">
          Generate a report and open it in your email client to send.
        </p>
      </div>

      <button
        onClick={handleGenerateReport}
        className="w-full py-3 rounded-2xl border-2 border-dashed border-emerald-300 dark:border-emerald-700 text-emerald-500 dark:text-emerald-400 text-[11px] font-black uppercase tracking-[0.15em] hover:bg-emerald-50 dark:hover:bg-emerald-900/20 transition-colors active:scale-[0.98] flex items-center justify-center gap-1.5"
      >
        <svg
          className="w-4 h-4"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
          strokeWidth={3}
          strokeLinecap="round"
        >
          <path d="M12 5v14M5 12h14" />
        </svg>
        Generate Report
      </button>

      {reportOpened && (
        <div className="mt-2 py-2 rounded-2xl bg-emerald-50 dark:bg-emerald-900/20 text-emerald-600 dark:text-emerald-400 text-[10px] font-black uppercase tracking-wider text-center animate-in fade-in duration-300">
          ✓ Report opened in email
        </div>
      )}
    </div>
  );
};

export default ReportSection;
